version: '3'

services:
  node:
    image: node:16
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./index.js:/app/index.js
      - ./jobs.db:/app/jobs.db
    env_file:
      - .env
    command: "node -r dotenv/config index.js"
