version: '3'

services:
  node:
    image: node:16
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./index.js:/app/index.js
      - ./database:/app/database
      - ./notifications:/app/notifications
      - ./strategies:/app/strategies
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    command: "node -r dotenv/config index.js"
